dss/cashflow/urls.py
from django.urls import path

from . import views


app_name = 'cashflow'

urlpatterns = [
    path(
        '',
        views.RecordListView.as_view(),
        name='index'
    ),
    path(
        'ajax/load-categories/',
        views.load_categories,
        name='ajax_load_categories'
    ),
    path(
        'ajax/load-subcategories/',
        views.load_subcategories,
        name='ajax_load_subcategories'
    ),
    path(
        'record/create/',
        views.RecordCreateView.as_view(),
        name='create_record'
    ),
    path(
        'record/<int:record_id>/',
        views.RecordDetailView.as_view(),
        name='record_detail'
    ),
    path(
        'record/<int:record_id>/edit/',
        views.RecordUpdateView.as_view(),
        name='edit_record'
    ),
    path(
        'record/<int:record_id>/delete/',
        views.RecordDeleteView.as_view(),
        name='delete_record'
    ),
    path(
        'status/',
        views.StatusListView.as_view(),
        name='status'
    ),
    path(
        'status/<int:status_id>/',
        views.StatusDetailView.as_view(),
        name='status_detail'
    ),
    path(
        'status/create/',
        views.StatusCreateView.as_view(),
        name='create_status'
    ),
    path(
        'status/<int:status_id>/edit/',
        views.StatusUpdateView.as_view(),
        name='edit_status'
    ),
    path(
        'status/<int:status_id>/delete/',
        views.StatusDeleteView.as_view(),
        name='delete_status'
    ),
    path(
        'type/',
        views.TypeListView.as_view(),
        name='type'
    ),
    path(
        'type/create/',
        views.TypeCreateView.as_view(),
        name='create_type'
    ),
    path(
        'type/<int:type_id>/edit/',
        views.TypeUpdateView.as_view(),
        name='edit_type'
    ),
    path(
        'type/<int:type_id>/delete/',
        views.TypeDeleteView.as_view(),
        name='delete_type'
    ),
    path(
        'type/<int:type_id>/',
        views.TypeDetailCategoryListView.as_view(),
        name='type_detail'
    ),
    path(
        'type/<int:type_id>/category/create/',
        views.CategoryCreateView.as_view(),
        name='create_category'
    ),
    path(
        'type/<int:type_id>/category/<slug:category_slug>/edit/',
        views.CategoryUpdateView.as_view(),
        name='edit_category'
    ),
    path(
        'type/<int:type_id>/category/<slug:category_slug>/delete/',
        views.CategoryDeleteView.as_view(),
        name='delete_category'
    ),
    path(
        'type/<int:type_id>/category/<slug:category_slug>/',
        views.CategoryDetailSubcategoryListView.as_view(),
        name='category_detail'
    ),
    path(
        'type/<int:type_id>/category/<slug:category_slug>/subcategory/create/',
        views.SubcategoryCreateView.as_view(),
        name='create_subcategory'
    ),
    path(
        (
            'type/<int:type_id>/category/<slug:category_slug>/'
            'subcategory/<slug:sub_slug>/edit/'
        ),
        views.SubcategoryUpdateView.as_view(),
        name='edit_subcategory'
    ),
    path(
        (
            'type/<int:type_id>/category/<slug:category_slug>/'
            'subcategory/<slug:sub_slug>/delete/'
        ),
        views.SubcategoryDeleteView.as_view(),
        name='delete_subcategory'
    ),
    path(
        (
            'type/<int:type_id>/category/<slug:category_slug>/'
            'subcategory/<slug:sub_slug>'
        ),
        views.SubcategoryDetailView.as_view(),
        name='subcategory_detail'
    ),
]

dss/dss/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.conf.urls.static import static
from django.conf import settings


handler404 = 'cashflow.views.page_not_found'
handler500 = 'cashflow.views.failure_server'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cashflow.urls', namespace='cashflow')),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('cashflow:index'),
        ),
        name='registration',
    ),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dss/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© Cashflow</p>    
  </footer>

dss/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'cashflow:index' %}">
        Cashflow
      </a>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav  nav-pills">
          <li class="nav-item">
          </li>
          <li class="nav-item">
          </li>
          {% if user.is_authenticated %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              {% if '/type/' in request.path %}
                <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'cashflow:create_status' %}">Создать статус</a></button>
                <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'cashflow:create_type' %}">Создать тип</a></button>
                <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'cashflow:status' %}">Список статусов</a></button>
              {% else %}
                <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'cashflow:create_record' %}">Создать запись</a></button>
                  <button 
                    type="button" 
                    class="btn btn-outline-primary"
                  >
                    <a 
                      class="text-decoration-none text-reset"
                      href="{% url 'cashflow:type' %}"
                    >
                      {% if not "/status/" in request.path%}Управление справочником {% else %} Список типов {% endif%}
                    </a>
                  </button>
              {% endif %}
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'logout' %}">Выйти</a></button>
            </div>
          {% else %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'login' %}">Войти</a></button>
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'registration' %}">Регистрация</a></button>
            </div>
          {% endif %}
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>

dss/templates/includes/item_card.html
<div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-body">
        <h5 class="card-title">{{ item.title }}</h5>
        <p class="card-text">{{ item.description|truncatewords:5 }}</p>
        {% if "/type/" in request.path %}
          <a href="{% url 'cashflow:type_detail' item.id %}" class="card-link">Подробнее</a>
        {% else %}
          <a href="{% url 'cashflow:status_detail' item.id %}" class="card-link">Подробнее</a>
        {% endif %}
      </div>
    </div>
  </div>

dss/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            << </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            >>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

dss/templates/includes/record_card.html
<div class="col d-flex justify-content-center">
    <div class="card" style="width: 30rem;">
      <div class="card-body">
        <h5 class="card-title">{% if record.status == None %} Нет статуса {% else %}{{ record.status }} {% endif%}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <small>
            {{ record.created_at|date:"d E Y" }}<br>
          </small>
        </h6>
        <p class="card-text">
          <b>Тип:</b> {{ record.type }} <br />
          <b>Категория:</b> {{ record.category }} <br />
          <b>Подкатегория:</b> {{ record.subcategory}} <br />
          <b>Сумма:</b> {{ record.amount}} рублей <br />
          <b>Комментарий:</b> {{ record.comment|truncatewords:5 }} <br />
        </p>
        <div class="mb-2">
          <div class="card-link">
            <a href="{% url 'cashflow:record_detail' record.id %}" class="card-link">Подробнее</a>
          </div>
        </div>
      </div>
    </div>
  </div>