dss/cashflow/urls.py
from django.urls import path

from . import views


app_name = 'cashflow'

urlpatterns = [
    path(
        '',
        views.RecordListView.as_view(),
        name='index'
    ),
    path(
        'ajax/load-categories/',
        views.load_categories,
        name='ajax_load_categories'
    ),
    path(
        'ajax/load-subcategories/',
        views.load_subcategories,
        name='ajax_load_subcategories'
    ),
    path(
        'record/create/',
        views.RecordCreateView.as_view(),
        name='create_record'
    ),
    path(
        'record/<int:record_id>/',
        views.RecordDetailView.as_view(),
        name='record_detail'
    ),
    path(
        'record/<int:record_id>/edit/',
        views.RecordUpdateView.as_view(),
        name='edit_record'
    ),
    path(
        'record/<int:record_id>/delete/',
        views.RecordDeleteView.as_view(),
        name='delete_record'
    ),
    path(
        'status/',
        views.StatusListView.as_view(),
        name='status'
    ),
    path(
        'status/<int:status_id>/',
        views.StatusDetailView.as_view(),
        name='status_detail'
    ),
    path(
        'status/create/',
        views.StatusCreateView.as_view(),
        name='create_status'
    ),
    path(
        'status/<int:status_id>/edit/',
        views.StatusUpdateView.as_view(),
        name='edit_status'
    ),
    path(
        'status/<int:status_id>/delete/',
        views.StatusDeleteView.as_view(),
        name='delete_status'
    ),
    path(
        'type/',
        views.TypeListView.as_view(),
        name='type'
    ),
    path(
        'type/create/',
        views.TypeCreateView.as_view(),
        name='create_type'
    ),
    path(
        'type/<int:type_id>/edit/',
        views.TypeUpdateView.as_view(),
        name='edit_type'
    ),
    path(
        'type/<int:type_id>/delete/',
        views.TypeDeleteView.as_view(),
        name='delete_type'
    ),
    path(
        'type/<int:type_id>/',
        views.TypeDetailCategoryListView.as_view(),
        name='type_detail'
    ),
    path(
        'type/<int:type_id>/category/create/',
        views.CategoryCreateView.as_view(),
        name='create_category'
    ),
    path(
        'type/<int:type_id>/category/<slug:category_slug>/edit/',
        views.CategoryUpdateView.as_view(),
        name='edit_category'
    ),
    path(
        'type/<int:type_id>/category/<slug:category_slug>/delete/',
        views.CategoryDeleteView.as_view(),
        name='delete_category'
    ),
    path(
        'type/<int:type_id>/category/<slug:category_slug>/',
        views.CategoryDetailSubcategoryListView.as_view(),
        name='category_detail'
    ),
    path(
        'type/<int:type_id>/category/<slug:category_slug>/subcategory/create/',
        views.SubcategoryCreateView.as_view(),
        name='create_subcategory'
    ),
    path(
        (
            'type/<int:type_id>/category/<slug:category_slug>/'
            'subcategory/<slug:sub_slug>/edit/'
        ),
        views.SubcategoryUpdateView.as_view(),
        name='edit_subcategory'
    ),
    path(
        (
            'type/<int:type_id>/category/<slug:category_slug>/'
            'subcategory/<slug:sub_slug>/delete/'
        ),
        views.SubcategoryDeleteView.as_view(),
        name='delete_subcategory'
    ),
    path(
        (
            'type/<int:type_id>/category/<slug:category_slug>/'
            'subcategory/<slug:sub_slug>'
        ),
        views.SubcategoryDetailView.as_view(),
        name='subcategory_detail'
    ),
]

dss/dss/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.conf.urls.static import static
from django.conf import settings


handler404 = 'cashflow.views.page_not_found'
handler500 = 'cashflow.views.failure_server'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cashflow.urls', namespace='cashflow')),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('cashflow:index'),
        ),
        name='registration',
    ),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dss/cashflow/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone


User = get_user_model()


class Record(models.Model):
    """Модель записи пользователя."""

    created_at = models.DateField(
        default=timezone.now,
        help_text='Время создания записи',
        verbose_name='Дата и время создания',
        editable=True
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор записи',
        help_text='Автор записи',
        related_name='records',
    )
    status = models.ForeignKey(
        'Status',
        on_delete=models.SET_NULL,
        verbose_name='Статус',
        help_text='статус записи',
        null=True,
        blank=True,
    )
    type = models.ForeignKey(
        'Type',
        on_delete=models.CASCADE,
        verbose_name='Тип',
        help_text='Тип записи',
        null=True,
        blank=False,
    )
    category = models.ForeignKey(
        'Category',
        on_delete=models.CASCADE,
        verbose_name='Категория',
        help_text='Категория записи',
        null=True,
        blank=False
    )
    subcategory = models.ForeignKey(
        'Subcategory',
        on_delete=models.CASCADE,
        verbose_name='Подкатегория',
        help_text='Подкатегория записи',
        null=True,
        blank=False

    )
    comment = models.TextField(
        blank=False,
        help_text='Текст комментария',
        verbose_name='Комментарий'
    )
    amount = models.PositiveIntegerField(
        default=0,
        help_text='Сумма, по умолчанию 0',
        verbose_name='Сумма',
        blank=False,
    )

    class Meta:
        ordering = ['id']
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'


class Status(models.Model):
    """Модель статуса денежных средств."""

    title = models.CharField(
        max_length=256,
        verbose_name='Название',
        help_text='Название статуса, максимальная длинна строки 256'
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор статуса',
        help_text='Автор статуса',
    )
    description = models.TextField(
        verbose_name='Описание'
    )

    class Meta:
        ordering = ['id']
        verbose_name = 'Статус денежных средств'
        verbose_name_plural = 'Статус денежных средств'

    def __str__(self):
        return self.title


class Type(models.Model):
    """Тип денежных средств."""

    title = models.CharField(
        max_length=256,
        verbose_name='Тип',
        help_text='Тип денежных средств, максимальная длинна строки 256'
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор Типа',
        help_text='Автор Типа',
        related_name='type',
    )
    description = models.TextField(
        verbose_name='Описание'
    )

    class Meta:
        ordering = ['id']
        verbose_name = 'Тип денежных средств'
        verbose_name_plural = 'Типы денежных средств'

    def __str__(self):
        return self.title


class Category(models.Model):
    """Модель категорий."""

    title = models.CharField(
        max_length=256,
        verbose_name='Название категории',
        help_text='Название категории, максимальная длинна строки 256'
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор категории',
        help_text='Автор категории',
        related_name='category',
    )
    description = models.TextField(
        verbose_name='Описание'
    )
    type = models.ForeignKey(
        Type,
        on_delete=models.CASCADE,
        verbose_name='Тип',
        help_text='Тип денежных средств',
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Идентификатор',
        help_text=('Идентификатор страницы для URL;'
                   ' разрешены символы латиницы, цифры, дефис'
                   ' и подчёркивание.')
    )

    class Meta:
        ordering = ['id']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title


class Subcategory(models.Model):
    """Модель подкатегорий."""

    title = models.CharField(
        max_length=256,
        verbose_name='Название подкатегории',
        help_text='Название подкатегории, максимальная длинна строки 256'
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор подкатегории',
        help_text='Автор подкатегории',
        related_name='subcategory',
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name='Категория',
        help_text='Категория денежных средств',
    )
    description = models.TextField(
        verbose_name='Описание'
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Идентификатор',
        help_text=('Идентификатор страницы для URL;'
                   ' разрешены символы латиницы, цифры, дефис'
                   ' и подчёркивание.')
    )

    class Meta:
        ordering = ['id']
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Подкатегории'

    def __str__(self):
        return self.title

dss/cashflow/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Category, Record, Type, Subcategory, Status

User = get_user_model()


class RecordFilterForm(forms.Form):
    """Форма для фильтрации записей."""

    start_date = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={"type": "date"}),
        label="Дата с"
    )
    end_date = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={"type": "date"}),
        label="Дата по"
    )
    status = forms.ModelChoiceField(
        queryset=Status.objects.all(),
        required=False,
        empty_label="Все статусы"
    )
    type = forms.ModelChoiceField(
        queryset=Type.objects.all(),
        required=False,
        empty_label="Все типы"
    )
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        required=False,
        empty_label="Все категории"
    )
    subcategory = forms.ModelChoiceField(
        queryset=Subcategory.objects.all(),
        required=False,
        empty_label="Все подкатегории"
    )


class RecordForm(forms.ModelForm):
    """Форма для записей."""

    created_at = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'type': 'date',
                'class': 'form-control',
            },
            format='%Y-%m-%d',
        ),
        required=False,
    )
    status = forms.ModelChoiceField(
        required=False,
        queryset=Status.objects.all(),
        empty_label='Выберите статус',
        widget=forms.Select(attrs={
            'class': 'form-control',
        })
    )
    type = forms.ModelChoiceField(
        queryset=Type.objects.all(),
        empty_label='Выберите тип',
        widget=forms.Select(attrs={
            'class': 'form-control',
        })
    )
    category = forms.ModelChoiceField(
        queryset=Category.objects.none(),
        empty_label='Сначала выберите тип',
        widget=forms.Select(attrs={
            'class': 'form-control',
            'id': 'id_category'
        })
    )
    subcategory = forms.ModelChoiceField(
        queryset=Subcategory.objects.none(),
        empty_label='Сначала выберите тип',
        widget=forms.Select(attrs={
            'class': 'form-control',
            'id': 'id_subcategory'
        })
    )
    amount = forms.IntegerField(
        required=True,
        min_value=0
    )
    comment = forms.Textarea()

    def __init__(self, *args, **kwargs):
        """Метод для корректной динамической подгрузки формы."""
        super().__init__(*args, **kwargs)
        if 'type' in self.data:
            try:
                type_id = int(self.data.get('type'))
                self.fields['category'].queryset = Category.objects.filter(
                    type_id=type_id
                )
            except (ValueError, TypeError):
                pass
        if 'category' in self.data:
            try:
                category_id = int(self.data.get('category'))
                self.fields[
                    'subcategory'
                ].queryset = Subcategory.objects.filter(
                    category_id=category_id
                )
            except (ValueError, TypeError):
                pass

    class Meta:
        model = Record
        fields = (
            'status',
            'type',
            'category',
            'subcategory',
            'amount',
            'comment',
            'created_at',
        )


class StatusForm(forms.ModelForm):
    """Форма для статусов."""

    class Meta:
        model = Status
        fields = ('title', 'description')


class TypeForm(forms.ModelForm):
    """Форма для типов."""

    class Meta:
        model = Type
        fields = ('title', 'description')


class CategoryForm(forms.ModelForm):
    """Форма для категорий."""

    class Meta:
        model = Category
        fields = ('title', 'description', 'slug')


class SubcategoryForm(forms.ModelForm):
    """Форма для подкатегорий."""

    class Meta:
        model = Subcategory
        fields = ('title', 'description', 'slug')

dss/templates/cashflow/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load widget_tweaks %}
{% block title %}
  {% if '/edit/' in request.path %}
    Редактирование записи
  {% elif "/delete/" in request.path %}
    Удаление записи
  {% else %}
    Добавление записи
  {% endif %}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        {% if '/edit/' in request.path %}
          Редактирование записи
        {% elif '/delete/' in request.path %}
          Удаление записи
        {% else %}
          Добавление записи
        {% endif %}
      </div>
      <div class="card-body">
        <form 
          method="post" 
          action="
            {% if '/edit/' in request.path %}
              {% url 'cashflow:edit_record' record.id %}
            {% elif '/delete/' in request.path %}
              {% url 'cashflow:delete_record' record.id %}
            {% else %}
              {% url 'cashflow:create_record' %}
            {% endif %}" 
          enctype="multipart/form-data"
        >
            {% csrf_token %}
            <div class="form-group">
              {% if "/delete/" in request.path %}
                <label class="col-md-6 form-label">Время создания:</label>
                <div class="col-sm-5 mb-4">
                  {{ form.created_at|add_class:"form-control"|attr:"readonly"|attr:"disabled"  }}
                </div>
                <label class="col-md-6 form-label">Статус:</label>
                <div class="col-sm-5 mb-4">
                  {{ form.status|add_class:"form-control"|attr:"readonly"|attr:"disabled" }}
                </div>
                <label class="col-md-6 form-label" for="id_type">Тип:</label>
                <div class="col-sm-5 mb-4">
                  {{ form.type|add_class:"form-control"|attr:"readonly"|attr:"disabled" }}
                </div>
                <label class="col-md-6 form-label" for="id_category">Категория:</label>
                <div class="col-sm-5 mb-4">
                  {{ form.category|add_class:"form-control"|attr:"readonly"|attr:"disabled" }}
                </div>
                <label class="col-md-6 form-label" for="id_subcategory">Подкатегория:</label>
                <div class="col-sm-5 mb-4">
                  {{ form.subcategory|add_class:"form-control"|attr:"readonly"|attr:"disabled" }}
                </div>
                <label class="col-md-6 form-label" for="id_subcategory">Сумма:</label>
                <div class="col-sm-5 mb-4">
                  {{ form.amount|add_class:"form-control"|attr:"readonly" }}
                </div>
                <label class="col-md-6 form-label" for="id_subcategory">Комментарий:</label>
                <div class="col-sm-5 mb-4">
                  {{ form.comment|add_class:"form-control"|attr:"readonly" }}
                </div>
              {% else %}
                <label class="col-md-6 form-label">Время создания:</label>
                <div class="col-sm-5 mb-4">
                  {{ form.created_at  }}
                </div>
                <label class="col-md-6 form-label">Статус:</label>
                <div class="col-sm-5 mb-4">
                  {{ form.status }}
                </div>
                <label class="col-md-6 form-label" for="id_type">Тип:</label>
                <div class="col-sm-5 mb-4">
                  {{ form.type }}
                </div>
                <label class="col-md-6 form-label" for="id_category">Категория:</label>
                <div class="col-sm-5 mb-4">
                  {{ form.category }}
                </div>
                <label class="col-md-6 form-label" for="id_subcategory">Подкатегория:</label>
                <div class="col-sm-5 mb-4">
                  {{ form.subcategory }}
                </div>
                <label class="col-md-6 form-label" for="id_subcategory">Сумма:</label>
                <div class="col-sm-5 mb-4">
                  {{ form.amount }}
                </div>
                <label class="col-md-6 form-label" for="id_subcategory">Комментарий:</label>
                <div class="col-sm-5 mb-4">
                  {{ form.comment }}
              {% endif %}
              {% bootstrap_button button_type="submit" content="Отправить"  %}
            </div>
        </form>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    $(document).ready(function () {
        function loadCategories(typeId, selectedCategoryId) {
            $.ajax({
                url: "{% url 'cashflow:ajax_load_categories' %}",
                data: {"type_id": typeId},
                success: function (data) {
                    $("#id_category").html('<option value="">Выберите категорию</option>');
                    $.each(data, function (index, category) {
                        var selected = category.id == selectedCategoryId ? 'selected' : '';
                        $("#id_category").append('<option value="' + category.id + '" ' + selected + '>' + category.title + '</option>');
                    });
                    if (selectedCategoryId) {
                        loadSubcategories(selectedCategoryId, {{ object.subcategory.id }});
                    }
                }
            });
        }
        function loadSubcategories(categoryId, selectedSubcategoryId) {
            $.ajax({
                url: "{% url 'cashflow:ajax_load_subcategories' %}",
                data: {"category_id": categoryId},
                success: function (data) {
                    $("#id_subcategory").html('<option value="">Выберите подкатегорию</option>');
                    $.each(data, function (index, subcategory) {
                        var selected = subcategory.id == selectedSubcategoryId ? 'selected' : '';
                        $("#id_subcategory").append('<option value="' + subcategory.id + '" ' + selected + '>' + subcategory.title + '</option>');
                    });
                }
            });
        }
        $("#id_type").change(function () {
            var typeId = $(this).val();
            loadCategories(typeId, null);
        });
        $("#id_category").change(function () {
            var categoryId = $(this).val();
            loadSubcategories(categoryId, null);
        });
        {% if '/edit/' in request.path %}
            var typeId = $("#id_type").val();
            var categoryId = {{ object.category.id }};
            if (typeId) {
                loadCategories(typeId, categoryId);
            }
        {% endif %}
    });
</script>
{% endblock %}

dss/templates/cashflow/create_guide.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  {% if "/edit/" in request.path %}
     Редактирование {% if "/subcategory/" in request.path %} подкатегории
    {% elif "/category/" in request.path %} категории
    {% elif "/status/" in request.path %} статуса
    {% else %} типа
    {% endif %}
  {% elif "/delete/" in request.path %}
    Удаление {% if "/subcategory/" in request.path %} подкатегории
    {% elif "/category/" in request.path %} категории
    {% elif "/status/" in request.path %} статуса
    {% else %} типа
    {% endif %}
  {% else %}
    Создание  {% if "/subcategory/" in request.path %} подкатегории
    {% elif "/category/" in request.path %} категории
    {% elif "/status/" in request.path %} статуса
    {% else %} типа
    {% endif %}
  {% endif %}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        {% if "/edit/" in request.path %}
          Редактирование {% if "/subcategory/" in request.path %} подкатегории
          {% elif "/category/" in request.path %} категории
          {% elif "/status/" in request.path %} статуса
          {% else %} типа
          {% endif %}
        {% elif "/delete/" in request.path %}
          Удаление {% if "/subcategory/" in request.path %} подкатегории
          {% elif "/category/" in request.path %} категории
          {% elif "/status/" in request.path %} статуса
          {% else %} типа
          {% endif %}
        {% else %}
          Добавление {% if "/subcategory/" in request.path %} подкатегории
          {% elif "/category/" in request.path %} категории
          {% elif "/status/" in request.path %} статуса
          {% else %} типа
          {% endif %}
        {% endif %}
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% if not '/delete/' in request.path %}
            {% bootstrap_form form %}
          {% else %}
            <h3>{{ form.instance.title }}</h3>
            <p>{{ form.instance.description|linebreaksbr }}</p>
          {% endif %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

dss/templates/cashflow/detail.html
{% extends "base.html" %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-body">
        <h5 class="card-title">
          {% if category %} 
            {{ category.title }} 
          {% elif type %}
            {{ type.title }} 
          {% elif subcategory %} 
            {{ subcategory.title }}
          {% elif record %}
            {% if  status_title == None %} Нет статуса {% else %} {{ status_title }} {% endif%}
          {% else %}
            {{ status.title}}
          {% endif %}
        </h5>
        <p class="card-text">
          {% if category %} 
            {{ category.description|linebreaksbr }} 
          {% elif type %} 
            {{ type.description|linebreaksbr }} 
          {% elif subcategory %} 
            {{ subcategory.description|linebreaksbr }}
          {% elif record %}
            <b>Время создания:</b> {{ record.created_at|date:"d E Y" }} </br>
            <b>Тип:</b> {{ type_title }} </br>
            <b>Категория:</b> {{ category_title }} </br>
            <b>Подкатегория:</b> {{ subcategory_title }} </br>
            <b>Сумма:</b> {{ record.amount }} рублей</br>
            <b>Комментарий:</b> {{ record.comment }} </br>
          {% else %}
            {{ status.description|linebreaksbr }} 
          {% endif %}
        </p>
        {% if subcategory or status or record %}
        <div class="mb-2">
          <div class="card-link">
            <a 
                class="btn btn-sm text-muted" 
                href="{% if status %}
                  {% url "cashflow:edit_status" status.id %}
                {% elif subcategory %}
                  {% url "cashflow:edit_subcategory" type_id category_slug subcategory.slug %}
                {% else %}
                  {% url "cashflow:edit_record" record.id %}
                {% endif %}" 
                role="button"
              >
                Редактировать 
                {% if subcategory %} 
                  подкатегорию 
                {% elif status %} 
                  статус  
                {% else %} 
                  запись 
                {% endif %}
            </a>
            <a 
            class="btn btn-sm text-muted" 
            href="{% if status %}
              {% url "cashflow:delete_status" status.id %}
            {% elif subcategory %}
              {% url "cashflow:delete_subcategory" type_id category_slug subcategory.slug %}
            {% else %}
              {% url "cashflow:delete_record" record.id %}
            {% endif %}" 
            role="button"
            >
              Удалить 
              {% if subcategory %} 
                подкатегорию 
              {% elif status %} 
                статус 
              {% else %} 
                запись 
              {% endif %}
            </a>
          </div>
        </div>
        {% else %}
          {% if status %}
          {% endif%}
          {% if not record%}
            <div class="mb-2">
              {% if category %}
                Подкатегории:
              {% else %}
                Категории:
              {% endif %}
              <ul>
                {% for item in page_obj %}
                  <li>
                    <a 
                      href="{% if category %}
                        {% url "cashflow:subcategory_detail" type_id category.slug item.slug %}
                      {% else %}
                        {% url "cashflow:category_detail" type.id item.slug %}
                      {% endif %}" 
                      class="card-link"
                    >
                      {{ item.title }}
                    </a>
                  </li>
                {% endfor %}
              </ul>
              <div class="card-link">
                <a 
                  class="btn btn-sm text-muted" 
                  href="{% if category %}
                    {% url "cashflow:create_subcategory" type_id category.slug %}
                  {% else %}
                    {% url "cashflow:create_category" type.id %}
                  {% endif %}" 
                  role="button"
                >
                  Создать
                  {% if category %} 
                    подкатегорию 
                  {% else %} 
                    категорию 
                  {% endif %}
                </a>
                {% if type %}
                  <a 
                    class="btn btn-sm text-muted" 
                    href="{% url "cashflow:edit_type" type.id  %}" 
                    role="button"
                  >
                    Редактировать тип
                  </a>
                  <a 
                    class="btn btn-sm text-muted" 
                    href="{% url "cashflow:delete_type" type.id  %}" 
                    role="button"
                  >
                    Удалить тип
                  </a>
                {% elif category %}
                  <a 
                    class="btn btn-sm text-muted" 
                    href="{% url "cashflow:edit_category" type_id category.slug  %}" 
                    role="button"
                  >
                    Редактировать категорию
                  </a>
                  <a 
                    class="btn btn-sm text-muted" 
                    href="{% url "cashflow:delete_category" type_id category.slug %}" 
                    role="button"
                  >
                    Удалить категорию
                  </a>
                {% endif %}
              </div>
            </div>
          {% endif %}
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

dss/templates/cashflow/index.html
{% extends "base.html" %}
{% block title %}
  Лента записей
{% endblock %}
{% block content %}
  <h1 class="text-center mb-5">Список записей </h1>
  <form method="get" class="mb-4">
    <div class="card p-3 shadow-sm">
        <div class="row g-3">
            <div class="col-md-3">
                <label class="form-label">Дата с:</label>
                {{ form.start_date }}
            </div>
            <div class="col-md-3">
                <label class="form-label">Дата по:</label>
                {{ form.end_date }}
            </div>
            <div class="col-md-3">
                <label class="form-label">Статус:</label>
                {{ form.status }}
            </div>
            <div class="col-md-3">
                <label class="form-label">Тип:</label>
                {{ form.type }}
            </div>
            <div class="col-md-3">
                <label class="form-label">Категория:</label>
                {{ form.category }}
            </div>
            <div class="col-md-3">
                <label class="form-label">Подкатегория:</label>
                {{ form.subcategory }}
            </div>
            <div class="col-md-3 d-flex align-items-end">
                <button type="submit" class="btn btn-primary w-100">Фильтровать</button>
            </div>
            <div class="col-md-3 d-flex align-items-end">
                <a href="{% url 'cashflow:index' %}" class="btn btn-secondary w-100">Сбросить</a>
            </div>
        </div>
    </div>
  </form>
  {% for record in page_obj %}
    <article class="mb-5">
      {% include "includes/record_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

dss/templates/cashflow/list.html
{% extends "base.html" %}
{% block title %}
  Справочник
{% endblock %}
{% block content %}
  <h1 class="text-center mb-5">Список 
    {% if "/type/" in request.path %}
      типов
    {% else %}
      статусов
      {% endif %}
    денежных средств
    </h1>
  {% for item in page_obj %}
    <article class="mb-5">
      {% include "includes/item_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}